services:

  postgres:
    image: quay.io/debezium/postgres:17
    container_name: postgres
    environment:
        POSTGRES_PASSWORD: postgres
    command: postgres -c config_file=/home/config/postgres.conf
    networks:
      - lan-network
    ports:
        - 5432:5432
    volumes:
        - ./postgres.conf:/home/config/postgres.conf
        - postgresdata:/var/lib/postgresql/data
    healthcheck:
        test: ['CMD-SHELL', 'pg_isready']
        interval: 10s
        timeout: 5s
        retries: 10

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=false
      - DISABLE_SECURITY_PLUGIN=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=C@r6Cam1M0e
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearchdata:/usr/share/opensearch/data
    ports:
        - 9200:9200
    networks:
      - lan-network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    container_name: api 
    image: ${DOCKER_REGISTRY-}debeziumpostgrestoopensearch-api
    build:
      context: ./api/.
      dockerfile: Dockerfile
    depends_on:
      opensearch:
        condition: service_healthy
    links:
      - opensearch
    networks:
      - lan-network
    ports:
      - 8081:8081

volumes:
  postgresdata:
    external: true
    name: postgresdata
  opensearchdata:
    external: true
    name: opensearchdata

networks:
  lan-network:
    driver: bridge