spring:
    application:
        name: 'connector'
debezium:
    postgres:
        host: your_postgres_host
        port: 5432
        database: your_database_name
        user: your_db_user
        password: your_db_password
        schema: public
        table-include-list: public.your_table